version: "3"

services:
    postgres:
        image: postgres:14.4
        volumes:
            - ./data/postgres/:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - django_net

    web:
        build:
            context: .
            args:
                - ENV=dev
        environment:
            - DJANGO_SETTINGS_MODULE=harvest_be.settings.dev
        volumes:
            - .:/code
        ports:
            - "${WEB_PORT:-8000}:8000"
        env_file:
            - .env
        tty: true
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - django_net
        command:
            - /bin/bash
            - -c
            - |
                cd source
                sleep 2
                python manage.py migrate
                python manage.py collectstatic --noinput
                python manage.py runserver 8000

networks:
    django_net:
        driver: bridge
