# Generated by Django 3.2.16 on 2022-10-09 02:39

import common.utilities.text
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orchard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=common.utilities.text.TextUtil.generate_uuid, primary_key=True, serialize=False, unique=True)),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=10)),
                ('picking_time', models.DateTimeField()),
                ('number_of_bins', models.PositiveIntegerField()),
                ('pay_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orchard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='harvest.orchard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
